""" This module defines constant literals.
"""

VNR_ACCEPTED = 1
VNR_FILTERED = 3
VNR_NO_SOLUTION = 0
VNR_INFEASIBLE = 2

VNR_ACCEPTANCE_THRESHOLD = 0.5

WRITE_AFTER_STRATEGY = 'WriteAfter\d+Events'
WRITE_AT_END_STRATEGY = 'WriteAtEnd'

CLASS_ARRIVAL_EVENT = 0
CLASS_DEPARTURE_EVENT = 1

CLASS_PHYSICAL_NETWORK = 1
CLASS_VIRTUAL_NETWORK = 2
CLASS_NETWORK = 0
CLASS_EMBEDDED_NETWORK = 3
CLASS_INVERSE_NETWORK = 4

PROCESS_TYPE_ARRIVAL = 'arrival'
PROCESS_TYPE_SERVICE = 'service'

ALGORITHM_MELO_SDP = 'SDP'
ALGORITHM_MELO_LB = 'LB'
ALGORITHM_MELO_WSDP = 'WSDP'
ALGORITHM_GREEDY = 'GR'
ALGORITHM_GRC = 'GONG'
ALGORITHM_MCR = 'MRC'
ALGORITHM_HF_GRC = 'HF_GONG'
ALGORITHM_HF_SDP = 'HF_SDP'
ALGORITHM_RNN_FILTER = 'RNN_FILTER'

NETWORK_MODEL_ERDOES_RENYI = 'ER'
NETWORK_MODEL_BARABASI_ALBERT = 'BA'
NETWORK_MODEL_STAR = 'STAR'
NETWORK_MODEL_WAXMAN = 'WAX'
NETWORK_MODEL_FULL_MESH = 'FM'

STORAGE_PEEWEE = 'mysql-peewee'
STORAGE_MYSQL = 'mysql'
STORAGE_PYMYSQL = 'mysql-pymysql'
STORAGE_FILE = 'file'
